const iconUrls = import.meta.glob('./**/*.svg', { eager: true, import: 'default' }) as Record<string, string>;
const iconRaws = import.meta.glob('./**/*.svg', { eager: true, query: '?raw', import: 'default' }) as Record<string, string>;

const iconDefinitions = [
  { name: 'drone', label: 'Drone', category: 'air', file: 'air/drone', source: 'Lucide', sourceIcon: 'drone' },
  { name: 'avion', label: 'Airplane', category: 'air', file: 'air/avion', source: 'Tabler Icons', sourceIcon: 'plane' },
  { name: 'helicoptere', label: 'Helicopter', category: 'air', file: 'air/helicoptere', source: 'Tabler Icons', sourceIcon: 'helicopter' },
  { name: 'montgolfiere', label: 'Hot-air balloon', category: 'air', file: 'air/montgolfiere', source: 'Tabler Icons', sourceIcon: 'air-balloon' },
  { name: 'parapente', label: 'Paraglider', category: 'air', file: 'air/parapente', source: 'Tabler Icons', sourceIcon: 'parachute' },
  { name: 'planeur', label: 'Glider', category: 'air', file: 'air/planeur', source: 'Phosphor Icons', sourceIcon: 'airplane-tilt' },
  { name: 'ulm', label: 'ULM', category: 'air', file: 'air/ulm', source: 'custom', sourceIcon: 'custom' },
  { name: 'wingsuit', label: 'Wingsuit', category: 'air', file: 'air/wingsuit', source: 'custom', sourceIcon: 'custom' },
  { name: 'jet-prive', label: 'Private jet', category: 'air', file: 'air/jet-prive', source: 'Tabler Icons', sourceIcon: 'plane-tilt' },
  { name: 'fusee', label: 'Rocket', category: 'air', file: 'air/fusee', source: 'Tabler Icons', sourceIcon: 'rocket' },
  { name: 'satellite', label: 'Satellite', category: 'air', file: 'air/satellite', source: 'Tabler Icons', sourceIcon: 'satellite' },

  { name: 'voilier', label: 'Sailboat', category: 'eau', file: 'eau/voilier', source: 'custom', sourceIcon: 'custom' },
  { name: 'bateau', label: 'Boat', category: 'eau', file: 'eau/bateau', source: 'custom', sourceIcon: 'custom' },
  { name: 'surf', label: 'Surfing', category: 'eau', file: 'eau/surf', source: 'custom', sourceIcon: 'custom' },
  { name: 'kayak', label: 'Kayak', category: 'eau', file: 'eau/kayak', source: 'custom', sourceIcon: 'custom' },
  { name: 'eau', label: 'Water', category: 'eau', file: 'eau/eau', source: 'custom', sourceIcon: 'custom' },

  { name: 'randonnee', label: 'Hiking', category: 'terre', file: 'terre/randonnee', source: 'Phosphor Icons', sourceIcon: 'person-simple-hike' },
  { name: 'marche', label: 'Walking', category: 'terre', file: 'terre/marche', source: 'Phosphor Icons', sourceIcon: 'person-simple-walk' },
  { name: 'running', label: 'Running', category: 'terre', file: 'terre/running', source: 'Phosphor Icons', sourceIcon: 'person-simple-run' },
  { name: 'vtt', label: 'VTT', category: 'terre', file: 'terre/vtt', source: 'Tabler Icons', sourceIcon: 'bike' },
  { name: 'velo', label: 'Bicycle', category: 'terre', file: 'terre/velo', source: 'Tabler Icons', sourceIcon: 'bike' },
  { name: 'moto', label: 'Motorcycle', category: 'terre', file: 'terre/moto', source: 'Tabler Icons', sourceIcon: 'motorbike' },
  { name: 'escalade', label: 'Climbing', category: 'terre', file: 'terre/escalade', source: 'custom', sourceIcon: 'custom' },
  { name: 'ski', label: 'Ski', category: 'terre', file: 'terre/ski', source: 'Phosphor Icons', sourceIcon: 'person-simple-ski' },
  { name: 'snowboard', label: 'Snowboard', category: 'terre', file: 'terre/snowboard', source: 'Phosphor Icons', sourceIcon: 'person-simple-snowboard' },
  { name: 'skateboard', label: 'Skateboard', category: 'terre', file: 'terre/skateboard', source: 'custom', sourceIcon: 'custom' },
  { name: 'camping', label: 'Camping', category: 'terre', file: 'terre/camping', source: 'Lucide', sourceIcon: 'tent' },
  { name: 'nature', label: 'Nature', category: 'terre', file: 'terre/nature', source: 'Lucide', sourceIcon: 'leaf' },
  { name: 'montagne', label: 'Mountain', category: 'terre', file: 'terre/montagne', source: 'Lucide', sourceIcon: 'mountain' },
  { name: 'foret', label: 'Forest', category: 'terre', file: 'terre/foret', source: 'Lucide', sourceIcon: 'trees' },
  { name: 'agriculture', label: 'Agriculture', category: 'terre', file: 'terre/agriculture', source: 'custom', sourceIcon: 'custom' },
  { name: 'terre', label: 'Land', category: 'terre', file: 'terre/terre', source: 'custom', sourceIcon: 'custom' },

  { name: 'train', label: 'Train', category: 'transport', file: 'transport/train', source: 'Tabler Icons', sourceIcon: 'train' },
  { name: 'metro', label: 'Metro', category: 'transport', file: 'transport/metro', source: 'Phosphor Icons', sourceIcon: 'train' },
  { name: 'tram', label: 'Tram', category: 'transport', file: 'transport/tram', source: 'Phosphor Icons', sourceIcon: 'tram' },
  { name: 'bus', label: 'Bus', category: 'transport', file: 'transport/bus', source: 'Tabler Icons', sourceIcon: 'bus' },
  { name: 'voiture', label: 'Car', category: 'transport', file: 'transport/voiture', source: 'Lucide', sourceIcon: 'car' },
  { name: 'moto', label: 'Motorcycle', category: 'transport', file: 'transport/moto', source: 'Tabler Icons', sourceIcon: 'motorbike' },
  { name: 'velo', label: 'Bicycle', category: 'transport', file: 'transport/velo', source: 'custom', sourceIcon: 'custom' },
  { name: 'vtt', label: 'VTT', category: 'transport', file: 'transport/vtt', source: 'custom', sourceIcon: 'custom' },
  { name: 'camion', label: 'Truck', category: 'transport', file: 'transport/camion', source: 'Tabler Icons', sourceIcon: 'truck' },
  { name: 'van', label: 'Van', category: 'transport', file: 'transport/van', source: 'Phosphor Icons', sourceIcon: 'van' },
  { name: 'camping-car', label: 'Camper van', category: 'transport', file: 'transport/camping-car', source: 'custom', sourceIcon: 'custom' },
  { name: 'bateau', label: 'Boat', category: 'transport', file: 'transport/bateau', source: 'Tabler Icons', sourceIcon: 'ship' },
  { name: 'avion', label: 'Airplane', category: 'transport', file: 'transport/avion', source: 'Tabler Icons', sourceIcon: 'plane' },
  { name: 'telepherique', label: 'Cable car', category: 'transport', file: 'transport/telepherique', source: 'Lucide', sourceIcon: 'cable-car' },

  { name: 'pov', label: 'POV', category: 'live', file: 'live/pov', source: 'custom', sourceIcon: 'custom' },
  { name: 'drone', label: 'Drone', category: 'live', file: 'live/drone', source: 'Lucide', sourceIcon: 'drone' },
  { name: 'fpv', label: 'FPV', category: 'live', file: 'live/fpv', source: 'custom', sourceIcon: 'custom' },
  { name: 'gopro', label: 'GoPro', category: 'live', file: 'live/gopro', source: 'custom', sourceIcon: 'custom' },
  { name: 'casque', label: 'Headset', category: 'live', file: 'live/casque', source: 'Phosphor Icons', sourceIcon: 'headset' },
  { name: 'camera', label: 'Camera', category: 'live', file: 'live/camera', source: 'Phosphor Icons', sourceIcon: 'video-camera' },
  { name: 'webcam', label: 'Webcam', category: 'live', file: 'live/webcam', source: 'Phosphor Icons', sourceIcon: 'webcam' },
  { name: 'live', label: 'Live', category: 'live', file: 'live/live', source: 'custom', sourceIcon: 'custom' },
  { name: 'replay', label: 'Replay', category: 'live', file: 'live/replay', source: 'Lucide', sourceIcon: 'refresh-cw + play' },
  { name: 'direct', label: 'Direct', category: 'live', file: 'live/direct', source: 'custom', sourceIcon: 'custom' },

  { name: 'cuisine', label: 'Cooking', category: 'metiers', file: 'metiers/cuisine', source: 'custom', sourceIcon: 'custom' },
  { name: 'boulanger', label: 'Baker', category: 'metiers', file: 'metiers/boulanger', source: 'custom', sourceIcon: 'custom' },
  { name: 'chef', label: 'Chef', category: 'metiers', file: 'metiers/chef', source: 'Lucide', sourceIcon: 'chef-hat' },
  { name: 'serveur', label: 'Server', category: 'metiers', file: 'metiers/serveur', source: 'custom', sourceIcon: 'custom' },
  { name: 'agriculteur', label: 'Farmer', category: 'metiers', file: 'metiers/agriculteur', source: 'custom', sourceIcon: 'custom' },
  { name: 'pompier', label: 'Firefighter', category: 'metiers', file: 'metiers/pompier', source: 'custom', sourceIcon: 'custom' },
  { name: 'policier', label: 'Police officer', category: 'metiers', file: 'metiers/policier', source: 'custom', sourceIcon: 'custom' },
  { name: 'medecin', label: 'Doctor', category: 'metiers', file: 'metiers/medecin', source: 'Tabler Icons', sourceIcon: 'stethoscope' },
  { name: 'dentiste', label: 'Dentist', category: 'metiers', file: 'metiers/dentiste', source: 'Phosphor Icons', sourceIcon: 'tooth' },
  { name: 'infirmier', label: 'Nurse', category: 'metiers', file: 'metiers/infirmier', source: 'Lucide', sourceIcon: 'shield-plus' },
  { name: 'architecte', label: 'Architect', category: 'metiers', file: 'metiers/architecte', source: 'Tabler Icons', sourceIcon: 'geometry' },
  { name: 'ingenieur', label: 'Engineer', category: 'metiers', file: 'metiers/ingenieur', source: 'custom', sourceIcon: 'custom' },
  { name: 'electricien', label: 'Electrician', category: 'metiers', file: 'metiers/electricien', source: 'Lucide', sourceIcon: 'bolt' },
  { name: 'menuisier', label: 'Cabinetmaker', category: 'metiers', file: 'metiers/menuisier', source: 'custom', sourceIcon: 'custom' },
  { name: 'plombier', label: 'Plumber', category: 'metiers', file: 'metiers/plombier', source: 'custom', sourceIcon: 'custom' },
  { name: 'mecanicien', label: 'Mechanic', category: 'metiers', file: 'metiers/mecanicien', source: 'Lucide', sourceIcon: 'wrench' },
  { name: 'pilote', label: 'Pilot', category: 'metiers', file: 'metiers/pilote', source: 'custom', sourceIcon: 'custom' },
  { name: 'conducteur-train', label: 'Train driver', category: 'metiers', file: 'metiers/conducteur-train', source: 'Tabler Icons', sourceIcon: 'train' },
  { name: 'taxi', label: 'Taxi', category: 'metiers', file: 'metiers/taxi', source: 'Tabler Icons', sourceIcon: 'taxi' },
  { name: 'chauffeur-poids-lourd', label: 'Truck driver', category: 'metiers', file: 'metiers/chauffeur-poids-lourd', source: 'Tabler Icons', sourceIcon: 'truck' },
  { name: 'professeur', label: 'Teacher', category: 'metiers', file: 'metiers/professeur', source: 'Lucide', sourceIcon: 'presentation' },
  { name: 'artisan', label: 'Craftsperson', category: 'metiers', file: 'metiers/artisan', source: 'custom', sourceIcon: 'custom' },
  { name: 'photographe', label: 'Photographer', category: 'metiers', file: 'metiers/photographe', source: 'Lucide', sourceIcon: 'camera' },
  { name: 'cameraman', label: 'Camera operator', category: 'metiers', file: 'metiers/cameraman', source: 'Phosphor Icons', sourceIcon: 'video-camera' },
  { name: 'musicien', label: 'Musician', category: 'metiers', file: 'metiers/musicien', source: 'Lucide', sourceIcon: 'music' },
  { name: 'dj', label: 'DJ', category: 'metiers', file: 'metiers/dj', source: 'custom', sourceIcon: 'custom' },
  { name: 'coiffeur', label: 'Hairdresser', category: 'metiers', file: 'metiers/coiffeur', source: 'Lucide', sourceIcon: 'scissors' },
  { name: 'fleuriste', label: 'Florist', category: 'metiers', file: 'metiers/fleuriste', source: 'Lucide', sourceIcon: 'flower-2' },

  { name: 'chantier', label: 'Construction site', category: 'metiers', file: 'metiers/chantier', source: 'custom', sourceIcon: 'custom' },

  { name: 'camera', label: 'Camera', category: 'passions', file: 'passions/camera', source: 'custom', sourceIcon: 'custom' },
  { name: 'concert', label: 'Concert', category: 'passions', file: 'passions/concert', source: 'custom', sourceIcon: 'custom' },

  { name: 'globe', label: 'Globe', category: 'navigation', file: 'navigation/globe', source: 'custom', sourceIcon: 'custom' },
  { name: 'localisation', label: 'Location', category: 'navigation', file: 'navigation/localisation', source: 'custom', sourceIcon: 'custom' },
  { name: 'profil', label: 'Profile', category: 'navigation', file: 'navigation/profil', source: 'custom', sourceIcon: 'custom' },

  { name: 'recherche', label: 'Search', category: 'interface', file: 'interface/recherche', source: 'custom', sourceIcon: 'custom' },
  { name: 'notifications', label: 'Notifications', category: 'interface', file: 'interface/notifications', source: 'custom', sourceIcon: 'custom' },
  { name: 'messages', label: 'Messages', category: 'interface', file: 'interface/messages', source: 'custom', sourceIcon: 'custom' },
  { name: 'parametres', label: 'Settings', category: 'interface', file: 'interface/parametres', source: 'custom', sourceIcon: 'custom' },
  { name: 'filtre', label: 'Filter', category: 'interface', file: 'interface/filtre', source: 'custom', sourceIcon: 'custom' },
];

export const vuvioIcons = iconDefinitions.map((item) => {
  const key = `./${item.file}.svg`;

  return {
    ...item,
    icon: iconUrls[key],
    svg: iconRaws[key],
  };
});
